export const AboutUs = () => {
    return (
        <div className="bg-[url('../src/images/back3.jpg')] md:h-screen bg-cover">
            <h1 className="text-white text-center text-6xl font-bold py-7">About Us!</h1>
            <div className="bg-white mx-5 text-center p-2">
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae quo ab alias, quam magnam quas perferendis sapiente a aliquam similique recusandae maiores voluptatem! Ipsa mollitia dignissimos rerum maxime excepturi voluptatibus voluptate officiis reprehenderit ex magnam odit molestias, perspiciatis quos consequatur autem numquam! Unde ea eum cum animi error doloremque pariatur quos ipsum. Hic dicta explicabo nisi impedit alias quas quis, provident fugiat omnis corrupti ratione? Dignissimos laboriosam, nobis, eius consequatur praesentium voluptatem id quis sunt dolorum velit magni quae aliquid atque, quaerat explicabo architecto? Temporibus a expedita ipsum nam, odio mollitia velit? Ea quaerat ipsum cumque, natus ut voluptas aliquam commodi nam illo accusamus doloribus iusto ducimus debitis qui a quis magnam? Dolor facilis numquam nihil dignissimos earum animi, laboriosam commodi vero nostrum, laudantium hic error dolorum, atque temporibus quas repudiandae voluptatem deleniti corrupti ea similique quod alias soluta magni vitae? Distinctio aliquam officiis assumenda harum reiciendis eveniet labore, fugit ipsa tenetur soluta? Ducimus, sapiente corporis amet, corrupti ullam asperiores ut at a harum odio, placeat veritatis? Libero tenetur numquam dolorum laboriosam hic culpa fuga iste voluptatibus atque exercitationem! Quisquam tempore tenetur dolore ratione blanditiis dolorem consequatur perspiciatis. Placeat enim, debitis et perspiciatis explicabo totam? Unde fugit iste earum natus nobis quam amet autem quod deserunt. Deserunt voluptate in ea tenetur nesciunt numquam dolores accusamus atque doloribus provident vitae porro, harum tempora eligendi ipsam minima qui reiciendis nostrum cumque asperiores, fugit pariatur. Perspiciatis numquam sequi illum voluptas adipisci temporibus est libero repudiandae iure iusto nemo qui ut exercitationem, nam officiis optio, magnam velit doloremque amet hic. Ipsa dolore maiores quis voluptate inventore eum deserunt recusandae asperiores! Perspiciatis neque vel consectetur officia maxime ab vero, accusantium sequi laborum expedita. At eos excepturi magni aut numquam debitis odit voluptas fugit veritatis labore repellendus asperiores, saepe perspiciatis error quibusdam quidem ipsa dolor! Pariatur!</p>
            </div>
        </div>
    )
}